
services:
  web:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/tools/:/var/www/yolo/
    restart: always



